=== Fabio-Pestana/ISEL-LEIM/2º Semestre/MOP/JV-A50756_MOP_TP4_ParteA/TP4/TP4/TP4/src/tps/out/production/tps/tps/tp4/Gymdados.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT Ginasio (Persons,Machines)+>
        <!ELEMENT Persons (Clientes+,Employees+)>
        <!ELEMENT Clientes (Client+)>
        <!ELEMENT Employees (Instrutor+, Employee+)>
        <!ELEMENT Client (Nome,Idade,Numero,Password,Genero,Peso,Altura,ClientPack,DataInscricao,TaxaDeAtividadeFisica,person)>
        <!ELEMENT Nome (#PCDATA)>
        <!ELEMENT Idade (#PCDATA)>
        <!ELEMENT Numero (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Genero (#PCDATA)>
        <!ELEMENT Peso (#PCDATA)>
        <!ELEMENT Altura (#PCDATA)>
        <!ELEMENT ClientPack (#PCDATA)>
        <!ELEMENT DataInscricao (#PCDATA)>
        <!ELEMENT TaxaDeAtividadeFisica (#PCDATA)>
        <!ELEMENT person (#PCDATA)>
        <!ELEMENT Instrutor (Nome,Idade,Numero,Password,Genero,Cargo,DataContratacao,YearsOfContract,Experiencia,PtClientes,person)>
        <!ELEMENT Cargo (#PCDATA)>
        <!ELEMENT DataContratacao (#PCDATA)>
        <!ELEMENT YearsOfContract (#PCDATA)>
        <!ELEMENT Experiencia (#PCDATA)>
        <!ELEMENT PtClientes (ClientNome)*>
        <!ELEMENT ClientNome (#PCDATA)>
        <!ELEMENT Employee (Nome,Idade,Numero,Password,Genero,Cargo,Salario,DataContratacao,YearsOfContract,person)>
        <!ELEMENT Salario (#PCDATA)>
        <!ELEMENT Machines (Machine)+>
        <!ELEMENT Machine (Nome,DataDeCompra,Custo)>
        <!ELEMENT DataDeCompra (#PCDATA)>
        <!ELEMENT Custo (#PCDATA)>

=== Fabio-Pestana/ISEL-LEIM/2º Semestre/MOP/JV-A50756_MOP_TP4_ParteA/TP4/TP4/TP4/out/production/TP4/Gymdados.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Ginasio SYSTEM "C:\Users\fabio\OneDrive\Ambiente de Trabalho\TP4\TP4\TP4\src\Gymdados.dtd">
<Ginasio>
        <Persons>
            <Clientes>
                <Client>
                    <Nome>Fabio Pestana</Nome>
                    <Idade>19</Idade>
                    <Numero>926987210</Numero>
                    <Password>Fabio2004</Password>
                    <Genero>Masculino</Genero>
                    <Peso>80</Peso>
                    <Altura>180</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2023-05-20</DataInscricao>
                    <TaxaDeAtividadeFisica>4</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Joao Silva</Nome>
                    <Idade>25</Idade>
                    <Numero>987654321</Numero>
                    <Password>Aaabb1234</Password>
                    <Genero>Masculino</Genero>
                    <Peso>90</Peso>
                    <Altura>192</Altura>
                    <ClientPack>1</ClientPack>
                    <DataInscricao>2020-01-25</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Maria Santos</Nome>
                    <Idade>30</Idade>
                    <Numero>976543210</Numero>
                    <Password>Xyzwq5678</Password>
                    <Genero>Feminino</Genero>
                    <Peso>65</Peso>
                    <Altura>160</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2022-04-12</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Pedro Costa</Nome>
                    <Idade>18</Idade>
                    <Numero>965432109</Numero>
                    <Password>Abcde9876</Password>
                    <Genero>Masculino</Genero>
                    <Peso>75</Peso>
                    <Altura>188</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2019-08-30</DataInscricao>
                    <TaxaDeAtividadeFisica>4</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Paulo Afonso</Nome>
                    <Idade>45</Idade>
                    <Numero>927210654</Numero>
                    <Password>PauloA1978</Password>
                    <Genero>Masculino</Genero>
                    <Peso>95</Peso>
                    <Altura>187</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2023-05-10</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Joao Maria</Nome>
                    <Idade>24</Idade>
                    <Numero>932109876</Numero>
                    <Password>JoaoMar1809</Password>
                    <Genero>Masculino</Genero>
                    <Peso>74</Peso>
                    <Altura>176</Altura>
                    <ClientPack>1</ClientPack>
                    <DataInscricao>2018-08-12</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Jose Santos</Nome>
                    <Idade>33</Idade>
                    <Numero>976125410</Numero>
                    <Password>JSanto5678</Password>
                    <Genero>Masculino</Genero>
                    <Peso>75</Peso>
                    <Altura>170</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2022-08-22</DataInscricao>
                    <TaxaDeAtividadeFisica>3</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Miguel Alcobia</Nome>
                    <Idade>28</Idade>
                    <Numero>918522660</Numero>
                    <Password>Benfica2004</Password>
                    <Genero>Masculino</Genero>
                    <Peso>65</Peso>
                    <Altura>179</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2023-01-30</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Rafael Mendes</Nome>
                    <Idade>17</Idade>
                    <Numero>929582301</Numero>
                    <Password>Form22234life</Password>
                    <Genero>Masculino</Genero>
                    <Peso>71</Peso>
                    <Altura>173</Altura>
                    <ClientPack>1</ClientPack>
                    <DataInscricao>2022-12-02</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Ana Costa</Nome>
                    <Idade>35</Idade>
                    <Numero>912345678</Numero>
                    <Password>AnaCosta1234</Password>
                    <Genero>Feminino</Genero>
                    <Peso>60</Peso>
                    <Altura>165</Altura>
                    <ClientPack>1</ClientPack>
                    <DataInscricao>2023-03-15</DataInscricao>
                    <TaxaDeAtividadeFisica>3</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Carlos Ferreira</Nome>
                    <Idade>42</Idade>
                    <Numero>923456789</Numero>
                    <Password>CarlosF1979</Password>
                    <Genero>Masculino</Genero>
                    <Peso>85</Peso>
                    <Altura>175</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2021-07-20</DataInscricao>
                    <TaxaDeAtividadeFisica>4</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Sofia Rodrigues</Nome>
                    <Idade>27</Idade>
                    <Numero>935678912</Numero>
                    <Password>Sofia2022</Password>
                    <Genero>Feminino</Genero>
                    <Peso>55</Peso>
                    <Altura>160</Altura>
                    <ClientPack>1</ClientPack>
                    <DataInscricao>2022-09-10</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Andre Santos</Nome>
                    <Idade>31</Idade>
                    <Numero>944567891</Numero>
                    <Password>Andre1989</Password>
                    <Genero>Masculino</Genero>
                    <Peso>80</Peso>
                    <Altura>180</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2022-11-05</DataInscricao>
                    <TaxaDeAtividadeFisica>3</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Mariana Oliveira</Nome>
                    <Idade>24</Idade>
                    <Numero>956789123</Numero>
                    <Password>Mariana2499</Password>
                    <Genero>Feminino</Genero>
                    <Peso>62</Peso>
                    <Altura>165</Altura>
                    <ClientPack>1</ClientPack>
                    <DataInscricao>2023-02-28</DataInscricao>
                    <TaxaDeAtividadeFisica>2</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Fernando Silva</Nome>
                    <Idade>40</Idade>
                    <Numero>967891234</Numero>
                    <Password>Fernando0421</Password>
                    <Genero>Masculino</Genero>
                    <Peso>90</Peso>
                    <Altura>185</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2021-04-15</DataInscricao>
                    <TaxaDeAtividadeFisica>4</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Carolina Santos</Nome>
                    <Idade>29</Idade>
                    <Numero>978912345</Numero>
                    <Password>Carolina0929</Password>
                    <Genero>Feminino</Genero>
                    <Peso>63</Peso>
                    <Altura>170</Altura>
                    <ClientPack>2</ClientPack>
                    <DataInscricao>2022-06-18</DataInscricao>
                    <TaxaDeAtividadeFisica>3</TaxaDeAtividadeFisica>
                    <person>cliente</person>
                </Client>
                <Client>
                    <Nome>Antonio Ribeiro</Nome>
                    <Idade>37</Idade>
                    <Numero>991234567</Numero>
                    <Password>Antonio0317</Password>
                    <Genero>Masculino</Genero>
